#!/bin/sh

#uvicorn --app-dir /app app:app --workers 2 --host 0.0.0.0 --port 8000 --log-config /app/logging.conf --log-level ${UVICORN_LOG_LEVEL}
uvicorn --app-dir /app app:app --workers 2 --host 0.0.0.0 --port 8000
